name: GitHub-Profile-3D-Contrib

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-github-profile-3d-contrib
    steps:
      - uses: actions/checkout@v4
      - uses: yoshi389111/github-profile-3d-contrib@0.7.1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          USERNAME: ${{ github.repository_owner }}
      - name: Setup GitHub Token for Git Authentication
        uses: actions/setup-git@v2
        with:
          github_token: ${{ secrets.GH_TOKEN }}
      - name: Commit & Push
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add -A .
          git commit -m "generated"
          git push
